### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by lapwat** [brocoders/extensive-react-boilerplate#133]
`tailwindcss` and `autoprefixer` are not in `package.json`

**Comment by Shchepotin** [comment]
We don't use `tailwindcss` and `autoprefixer`. Please provide more info about your issue

**Comment by lapwat** [comment]
I had to install both to run the `pnpm run dev ` command. Otherwise the command crashes with the `missing tailwindcss/autoprefixer` error. After I install both packages, the error is gone and the run command starts correctly.

**Comment by lapwat** [comment]
I got this error while running other project boilerplates.

It must be an error with my config.
