### ISSUE TITLE
Assistance with OAuth 2.0 Configuration for Local Development

### ISSUE THREAD

**Issue by KevinCotoCarrera** [brocoders/extensive-react-boilerplate#206]
### Subject of the issue
Trouble configuring OAuth 2.0 for local development environment on `http://localhost:3001`

### Expected behaviour
Being able to select my google account

### Actual behaviour
Blank page in url:  https://accounts.google.com/gsi/select?client_id=${my_client_id}apps.googleusercontent.com&ux_mode=popup&ui_mode=card&as=VdS0KEGuH3aPP%2FPwN9lsmA&channel_id=ccf306d44944a42f7f4461300dcb735c9ff16595c89724babb7f8c53757c9224&origin=http%3A%2F%2Flocalhost%3A3001
### Additional context
I am currently developing a web application using this boilerplate running on `localhost:3001`. I have set up my Google Cloud OAuth 2.0 client IDs correctly, but when I try to authenticate using Google's OAuth service, it does not work as expected. Here's how I've configured my OAuth credentials in the Google Cloud Console:

- Authorized JavaScript origins: `http://localhost:3001`
- Authorized redirect URIs: `http://localhost:3001`

Despite this configuration, I am facing issues with the authentication flow. I have checked the following:

- The application is running on the correct port and uses the `http` protocol.
- The client ID is correctly inserted into the code.
- The redirect URIs in Google Cloud Console appear to be correctly configured.
- Browser cache has been cleared, and I've also tried using an incognito window.

I am following the example provided in [link to the example or documentation].

Could you please provide some guidance on what might be going wrong or any additional steps I need to take for local development setup?

**Comment by Shchepotin** [comment]
@KevinCotoCarrera please try to add `http://localhost` to authorized JavaScript origins. Like here:

<img width="860" alt="image" src="https://github.com/brocoders/extensive-react-boilerplate/assets/6001723/39358495-2c14-4dc3-8685-a33b920bc9de">

More info here: https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid#get_your_google_api_client_id

<img width="859" alt="image" src="https://github.com/brocoders/extensive-react-boilerplate/assets/6001723/f7b0df71-7be3-4869-8a2e-5f514dce1706">

**Comment by KevinCotoCarrera** [comment]
Hey @Shchepotin 
Apologies for the late reply, work has had me tied up.

I wanted to let you know I tried your suggestion on the GitHub issue when I could and it worked out great. Really appreciate the help.
